apiVersion: 1

datasources:
  - name: tutorial_mysql
    type: mysql
    url: host.docker.internal:3306
    database: tutorial_mysql
    user: root
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: root
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    jsonData:
      httpMethod: POST
      timeInterval: 1s
