version: '3.8'

services:
  prometheus-grafana-tutorial-mysql:
    container_name: prometheus-grafana-tutorial-mysql
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: tutorial_mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  prometheus-grafana-tutorial:
    image: prometheus-grafana-tutorial
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          memory: 128M

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:9.3.2
    container_name: grafana
    restart: unless-stopped
    volumes:
      - './datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml'
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: { }
