global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1s
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "prometheus-grafana-tutorial"
    scrape_interval: 1s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
